name: flutter_biometrics_example
description: Demonstrates how to use the flutter_biometrics plugin.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_biometrics:
    path: ../

flutter:
  uses-material-design: true